(* DO NOT EDIT THIS FILE *)
(* DO NOT EDIT THIS FILE *)
(* DO NOT EDIT THIS FILE *)
(* This file contains functions used to test the SML code you write *)
fun pass_fail x = if x then "Pass" else "\t\t**Fail**";

fun error_print (test_name) = print ("Runtime error in test of " ^test_name^"\n");

fun test(test_id, test_name, func, input, expected_output) =
let
 
 val _ = print("\nTest "^ test_id ^": "^ test_name ^": ")
 val _ = print(pass_fail (func(input) = expected_output)^"\n") handle _ => error_print(test_name)
in
    ()
end;

fun test_real(test_id, test_name, func, input, expected_output) =
let
 
 val _ = print("\nTest "^ test_id ^": "^ test_name ^": ")
 val _ = print(pass_fail (Real.abs(func(input) - expected_output) < 0.001)^"\n") handle _ => error_print(test_name)
in
    ()
end;